project:
  type: website

website:
  title: "Deep Learning Notes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Loss Functions"
        contents:
          - loss/likelihood.qmd
          - loss/mle-to-nll.qmd
          - loss/gaussian-to-mse.qmd

format:
  html:
    theme: cosmo
    math: mathjax
