project:
  type: website

website:
  title: "Deep Learning Notes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Loss Functions"
        contents:
          - loss/likelihood.qmd
      - section: "Neural Networks"
        contents:
          - neural-networks/understanding-neural-networks.qmd

format:
  html:
    theme: cosmo
    math: mathjax
    # css: styles.css
